# Tensor

In [5]:
"""
tensor는 array나 matrix와 매우 유사한 특수 자료구조
pytorch에서는 텐서를 사용하여 모델의 입력과 출력
그리고 모델의 매개변수들을 모두 부호화(encode)한다.

텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면
넘파이의 ndarray와 유사하다.
실제로 텐서와 넘파이 배열은 종종 동일한 내부(underly) 메모리를 공유할 수 있어,
데이터를 복수할 필요가 없다.

텐서는 또한 자동 미분에 최적화되어 있다.
ndarray에 익숙하다면 TensorAPI를 바로 사용할 수 있다.
"""
import torch
import numpy as np

# 텐서 초기화

In [6]:
"""
텐서는 여러가지 방법으로 초기화할 수 있다.
"""

# 데이터로부터 직접 생성하기
# 데이터의 자료형은 자동으로 유추한다.
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data


tensor([[1, 2],
        [3, 4]])

In [8]:
import numpy as np
# 넘파이 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
# x_np
print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [8]:
# 다른 텐서로부터 생성하기
# 명시적으로 재정의(override)하지 않는다면, 
# 인자로 주어진 텐서의 속성(shape, datatype)을 유지한다.

x_ones = torch.ones_like(x_data) # x_data 속성 override
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data 속성 override
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5080, 0.7004],
        [0.5492, 0.7089]]) 



In [11]:
# 무작위 또는 상수값 사용
# shape는 텐서의 차원을 나타내는 튜플로,
# 아래의 함수들에서는 출력 텐서의 차원을 결정
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor : \n {ones_tensor} \n")
print(f"Zeros Tensor :\n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.5569, 0.0729, 0.3661],
        [0.0425, 0.6927, 0.3146]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor :
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# 텐서의 속성(Attribute)

In [12]:
"""
텐서의 속성은 텐서의 모양, 자료형 및 어느 장치에 저장되는지를 나타낸다.
"""
tensor = torch.rand(3,4)

print(f"shape of tensor: {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


shape of tensor: torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on: cpu


# 텐서 연산(operation)

In [13]:
"""
전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산,
선형대수, 랜덤 샘플링 등, 100가지 이상의 텐서 연산

각 연산들은 gpu에서 실행할 수 있음
기본적으로 텐서는 cpu에 생성됨.
gpu 가용성을 확인한 뒤 .to 메소드를 사용하면 
gpu로 텐서를 명시적으로 이동할 수 있음

장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서
비용이 많이든다는 것을 명심
"""

# gpu가 존재하면 텐서를 이동한다.
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [9]:
# numpy식의 표준 인덱싱과 슬라이싱
tensor = torch.rand(4,4)
print('Fist row', tensor[0])
print('First column', tensor[:, 0])
print('last column', tensor[..., -1])
tensor[:,1] = 0
print(tensor)


Fist row tensor([0.9738, 0.4507, 0.8900, 0.6536])
First column tensor([0.9738, 0.8660, 0.4951, 0.7895])
last column tensor([0.6536, 0.8252, 0.3392, 0.3372])
tensor([[0.9738, 0.0000, 0.8900, 0.6536],
        [0.8660, 0.0000, 0.4515, 0.8252],
        [0.4951, 0.0000, 0.2855, 0.3392],
        [0.7895, 0.0000, 0.7085, 0.3372]])


In [10]:
# 텐서 합치기
# torch.cat을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있음
# torch.cat과 미묘하게 다른 또 다른 텐서 결합인 torch.stack도 참고
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1) # 가로로 붙인 결과 출력

tensor([[0.9738, 0.0000, 0.8900, 0.6536, 0.9738, 0.0000, 0.8900, 0.6536, 0.9738,
         0.0000, 0.8900, 0.6536],
        [0.8660, 0.0000, 0.4515, 0.8252, 0.8660, 0.0000, 0.4515, 0.8252, 0.8660,
         0.0000, 0.4515, 0.8252],
        [0.4951, 0.0000, 0.2855, 0.3392, 0.4951, 0.0000, 0.2855, 0.3392, 0.4951,
         0.0000, 0.2855, 0.3392],
        [0.7895, 0.0000, 0.7085, 0.3372, 0.7895, 0.0000, 0.7085, 0.3372, 0.7895,
         0.0000, 0.7085, 0.3372]])


In [12]:
# 산술 연산 Arithmetic operations

# 두 텐서 간의 행렬 곱(matrix multiplication) 계산
# y1, y2, y3은 모두 같은 값을 갖는다

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
print(torch.matmul(tensor, tensor.T, out=y3))

# 요소별 곱(element-wise product)을 계산
# z1, z2, z3은 모두 같은 값
z1 = tensor * tensor`
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)

print(torch.mul(tensor, tensor, out=z3))




tensor([[2.1677, 1.7845, 0.9580, 1.6199],
        [1.7845, 1.6347, 0.8376, 1.2819],
        [0.9580, 0.8376, 0.4418, 0.7076],
        [1.6199, 1.2819, 0.7076, 1.2391]])
tensor([[0.9483, 0.0000, 0.7921, 0.4272],
        [0.7500, 0.0000, 0.2039, 0.6809],
        [0.2452, 0.0000, 0.0815, 0.1151],
        [0.6234, 0.0000, 0.5020, 0.1137]])
